// internal/ui/gototop_test.go
package ui

import (
	"testing"

	tea "charm.land/bubbletea/v2"

	"github.com/gammons/slk/internal/ui/help"
	"github.com/gammons/slk/internal/ui/messages"
	"github.com/gammons/slk/internal/ui/sidebar"
)

// TestTopKeyIsAdvertisedInHelp pins why the missing handler mattered:
// the help modal is generated by reflecting over the keymap, so a
// binding with help text is shown to users whether or not anything
// dispatches on it. "gg / top" has always been on that list.
func TestTopKeyIsAdvertisedInHelp(t *testing.T) {
	a := NewApp()
	for _, e := range help.FromKeyMap(a.keys) {
		if e.Desc == "top" {
			return
		}
	}
	t.Fatal(`the help modal no longer lists "top"; this test guards the binding that pairs with it`)
}

// TestGoToTopMovesSidebar covers the panel with the simplest
// observable state.
func TestGoToTopMovesSidebar(t *testing.T) {
	a := NewApp()
	a.width, a.height = 120, 30
	a.focusedPanel = PanelSidebar
	items := make([]sidebar.ChannelItem, 0, 12)
	for i := 0; i < 12; i++ {
		items = append(items, sidebar.ChannelItem{
			ID: string(rune('a' + i)), Name: "chan", Type: "channel",
		})
	}
	a.sidebar.SetItems(items)
	_ = a.View()

	a.sidebar.GoToBottom()
	if a.sidebar.IsThreadsSelected() {
		t.Skip("fixture did not produce a movable sidebar selection")
	}

	handleNormalMode(a, tea.KeyPressMsg{Code: 'g', Text: "g"})

	// Row 0 of the sidebar is the synthetic Threads row, so "at the
	// top" is that row being selected.
	if !a.sidebar.IsThreadsSelected() {
		t.Errorf("g left the sidebar selection on %q instead of the first row",
			a.sidebar.SelectedID())
	}
}

// TestGoToTopScrollsChannelHistory covers the messages pane.
func TestGoToTopScrollsChannelHistory(t *testing.T) {
	a := NewApp()
	a.width, a.height = 120, 24
	a.focusedPanel = PanelMessages
	msgs := make([]messages.MessageItem, 0, 80)
	for i := 0; i < 80; i++ {
		msgs = append(msgs, messages.MessageItem{
			TS: "1700000000.0000" + string(rune('0'+i%10)), UserName: "someone", Text: "line",
		})
	}
	a.messagepane.SetMessages(msgs)
	_ = a.View()

	a.messagepane.GoToBottom()
	if a.messagepane.AtTop() {
		t.Skip("fixture is not long enough to move within")
	}

	handleNormalMode(a, tea.KeyPressMsg{Code: 'g', Text: "g"})

	if !a.messagepane.AtTop() {
		t.Error("g did not take the channel history to the top")
	}
}
